export const T = {
  cream: "#FBF5EC",
  paper: "#FEF7ED",
  warmIvory: "#F9F1E6",
  peach: "#E8A87C",
  coral: "#E07A5F",
  mint: "#B8D8D0",
  mintDeep: "#7FBFB0",
  lavender: "#C8B8D8",
  purple: "#6D4C91",
  brown: "#5A3E2B",
  brownLight: "#8B6F55",
  brownMid: "#A08060",
  brownPale: "#C4A882",
  kakao: "#FEE500",
  kakaoBrown: "#3C1E1E",
  white: "#FFFFFF",
  fontSerif: "'Nanum Myeongjo', 'Noto Serif KR', Georgia, serif",
  fontSans: "'Noto Sans KR', 'Apple SD Gothic Neo', sans-serif",
} as const;
